name: Deploy Azure Function App

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Zip backend
        run: |
          cd backend
          zip -r ../function.zip .

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: chinmay-visitor-counter   # 👈 Replace with your Azure Function App name
          package: function.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
