name: Deploy Azure Function App

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # or your Node.js version

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: chinmay-visitor-counter     # replace with your Azure Function App name
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./backend
