name: Deploy Backend (Azure Function)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/setup-azure@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group YourResourceGroupName \
            --name YourFunctionAppName \
            --src backend.zip

      - name: Zip backend files
        run: |
          zip -r backend.zip backend
